# Example requests

### Create item
POST http://localhost:9090 HTTP/1.1
content-type: application/json

{
    "id": 0,
    "name": "Tea",
    "description": "black",
    "price": 1.90,
    "sku": "fdfd54"
}

### GET All items
GET http://localhost:9090

###Update an item
PUT http://localhost:9090/1
content-type: application/json

{   
   "name": "Latte",
    "description": "Frothy milky coffee",
    "price": 2.65,
    "sku": "abc323"   
}
