# Example requests

### Create item
POST http://localhost:9090 HTTP/1.1
content-type: application/json

{
    "name": "Tea",
    "description": "black",
    "price": 1.90,
    "sku": "fdf-dwe-qwer"
}

### GET All items
GET http://localhost:9090

###Update an item
PUT http://localhost:9090/1
content-type: application/json

{   
   "name": "Latte",
    "description": "Frothy milky coffee",
    "price": 2.65,
    "sku": "abc-sdf-qwe"   
}

###Update an item
PUT http://localhost:9090/2
content-type: application/json

{   
   "name": "Espresso",
    "description": "Short and strong coffee without milk",
    "price": 1.99,
    "sku": "asc-ddf-rwe"   
}
